### ISSUE TITLE
Warning in console on Node 7.0.0

### ISSUE THREAD

**Issue by buildbreakdo** [sindresorhus/username#12]
Just a heads up, seeing warning in console on Node 7.0.0:

(node:44604) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by sindresorhus** [comment]
Closing as they removed the warning in the latest v7 version.
