### ISSUE TITLE
os.UserInfo does not honor SUDO_USER

### ISSUE THREAD

**Issue by ekristen** [sindresorhus/username#16]
if you are using this in a script called with sudo, it'll always return root on linux because os.UserInfo doesn't honor SUDO_USER. It would be nice to return SUDO_USER first if available instead of UserInfo

**Comment by kevva** [comment]
I would open an issue about it on https://github.com/nodejs/node/issues/new.

Do we want to fix it in here in the meantime @sindresorhus? Could probably just switch place with `getEnvVar()` which I think would be more correct anyway. node is probably not checking for `C9_USER` for example.

**Comment by sindresorhus** [comment]
> Could probably just switch place with getEnvVar() which I think would be more correct anyway. node is probably not checking for C9_USER for example.

👍
