### ISSUE TITLE
User x Root

### ISSUE THREAD

**Issue by rafaelquines** [sindresorhus/username#18]
I use this lib in a project, and until previous version, it works. But now, the behavior changed.

Before, when I ran my code normally, username.sync() returned 'myuser'. But, when I ran with sudo, it returns 'root'.

In the last version, username.sync() returns 'myuser' always, independent of sudo.

Is it correct behavior? If yes, I will changed my code to use 'process.env.USER".

Thanks

**Comment by sindresorhus** [comment]
Intentional yes, https://github.com/sindresorhus/username/issues/16

**Comment by rafaelquines** [comment]
Thank you so much.
