### ISSUE TITLE
npm shrinkwrap error

### ISSUE THREAD

**Issue by hwclass** [sindresorhus/username#2]
Hi all,

During the getting shrinkwrap file by 'npm shrinkwrap', it corrupts and logs the following:

`npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: username@2.1.0 <PATH>`

That's why, I cannot reproduce the shrinkwrap.json file to create a dependency tree file for the application.

Thanks.

**Comment by sindresorhus** [comment]
npm support here: https://github.com/npm/npm/issues
