### ISSUE TITLE
Make it return something in Docker

### ISSUE THREAD

**Issue by raido** [sindresorhus/username#21]
https://github.com/sindresorhus/username/blob/master/index.js#L29

Above userInfo() call should be wrapped in try catch block. 

This causes crash when running for example in docker container like:

`docker run --user $(id -u): $(id -g) ...`

Because user in docker then will be without $HOME and username both.

**Comment by raido** [comment]
Example how this has been addressed here: 

https://github.com/moleculerjs/moleculer/pull/396/files#diff-38423b3db1f1c2a43666c7ad898ba126R45

**Comment by sindresorhus** [comment]
The `os.userInfo()` method is not documented to throw. You should open an issue on Node.js about this instead. This looks like a Node.js bug.

**Comment by raido** [comment]
It seems it is expected behaviour from Node and just not documented.

I am not sure now should we catch and return empty object or return rejected promise and let consumers of this package deal with the problem.

**Comment by sindresorhus** [comment]
Thanks for opening the issue on Node.js. I have worked around the issue on my end now.

**Comment by raido** [comment]
This will not work in docker context we have here. Yes, it will not hard crash but it will not return single line result either.

Now when `os.userInfo` throws, we end up calling `id -un` which now returns following as stdout:

```
id: cannot find name for user ID <userId>
<userId>
```

The `-n` argument has no username to return.

**Comment by sindresorhus** [comment]
Then I don't really know a way to get the username in Docker. I don't use Docker, but PR welcome if you can think of a way.

**Comment by sindresorhus** [comment]
Maybe something like this: https://stackoverflow.com/a/38927208/64949

**Comment by raido** [comment]
I am not sure there is a way. There is no actual user in the container when `—user` flag is present.

I guess if we could detect the situation some how and just return `user-<id>` as resulting string, it would be close enough.

I have some ideas, I’ll try them out.

**Comment by raido** [comment]
I opened a PR as possible solution.
