### ISSUE TITLE
returning undefined in .exe app-installer built by electron-builder

### ISSUE THREAD

**Issue by barbalex** [sindresorhus/username#27]
I am using username for an electron app.

Inside index.js I tried to import it:

```
const { username } = require('username')
```

That did not go well:
<img width="419" alt="2023-01-25_18h35_57" src="https://user-images.githubusercontent.com/669783/214639447-d83457bc-68b2-4e00-9dba-71a962e10b4b.png">

So I followed vite's advice and dynamically imported:
```
const { username } = await import('username')
userName = await username()
```

That seemed to work fine, i.e. userName is `alexa`, as expected. In dev mode. And also: When using the .exe created in the `win-unpacked` folder of the release (built by electron-builder).

Here is where things get puzzling.

I then used the .exe app-installer created by electron-builder to install the app. When _this_ app is opened, userName is `undefined`.

Why could this be?

**Comment by sindresorhus** [comment]
This is not the place to ask for Electron / electron-builder support. This package was made for Node.js. Any usage outside of that is not something I can provide support for.

**Comment by barbalex** [comment]
Well, thanks for providing so many great node tools
