### ISSUE TITLE
was it intentional to lose support for 0.10 and 0.12?

### ISSUE THREAD

**Issue by sam-github** [sindresorhus/username#7]
Your package.json still says `>= 0.10`, but its use of const is invalid in at least `<= 0.12`. I tried changing const to var, and the ava tests pass, though xo enforces an unportable coding style, so it fails.

We've backdated to 1.x, but if it was intentional, updating the package.json would be helpful.

```
s/username (master * u=) % npm test

> username@2.2.0 test /Users/sam/s/username
> xo && ava


  index.js:2:1
  ✖   2:1  Unexpected var, use let or const instead.  no-var
  ✖   3:1  Unexpected var, use let or const instead.  no-var
  ✖   4:1  Unexpected var, use let or const instead.  no-var
  ⚠  48:4  Unexpected todo comment.                   no-warning-comments

  3 errors
  1 warning
npm ERR! Test failed.  See above for more details.
```

Strangely, all those fancy unicode chars above show up as plain whitespace in my terminal... but showed up when I cut-n-pasted the whitespace into github.

**Comment by sindresorhus** [comment]
Oh yeah. That's an oversight. The module requires Node.js 4 or later. See: https://github.com/sindresorhus/username/commit/80c8ad443d38b5b92ae8e413b2dfec9b2400f2e6
